const list = [
    {
      id: 1,
      title: "Album 1",
      author: "by Sanjay Gupta | 25 April 2018",
      price: 100,
      img: 'https://prasadyash2411.github.io/ecom-website/img/Album%201.png',


      amount: 1,
    },
    {
      id: 2,
      title: 'Album 2',
      author: "by Sanjay Gupta  | 1 September 2020",
      price: 50,
      img:  'https://prasadyash2411.github.io/ecom-website/img/Album%202.png',
      amount: 1,
    },
    {
      id: 3,
      title: 'Album 3',
      author: "by Sanjay Gupta  | 25 November 2018",
      price: 70,
      img: 'https://prasadyash2411.github.io/ecom-website/img/Album%203.png',
      amount: 1,
    },
    {
      id: 4,
      title: 'Album 4',
      author: "by Sanjay Gupta | 25 April 2018",
      price: 100,
      img: 'https://prasadyash2411.github.io/ecom-website/img/Album%204.png',
      amount: 1,
    },
    {
      id: 5,
      title: "Coffee Cup",
      author: "by Sanjay Gupta  | 1 January 2018",
      price: 50,
      img: "https://prasadyash2411.github.io/ecom-website/img/Cofee.png",
      amount: 1,
    },
    {
      id: 6,
      title: "T-shirt",
      author: "by Sanjay Gupta| 30 September 2020",
      price: 100,
      img: "https://prasadyash2411.github.io/ecom-website/img/Shirt.png",
      amount: 1,
    },
    {
      id: 7,
      title: "ASUS Laptop",
      author: "by ASUS Company| 1 January 2021",
      price: 20000,
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTY-O8N0CNUyOW4Wmck_rCUXTGBs6gfSDH6t-VBMMBqTxIcOV7KokkJeBgsnASQQZwaghgJC0qr_Yo&usqp=CAc",
      amount: 1,
    },
    {
      id: 8,
      title: "Lenovo Laptop",
      author: "by Lenovo Company | 6 December 2020",
      price: 30000,
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSqzLfwLBGvTH5cBzzgjDSdSGRWLcvjXw5DURO8vYt5HdHZ3wjNI2atnMJ78t8SZGMEV4fPJMIeCy4&usqp=CAc",
      amount: 1,
    },
    {
      id: 9,
      title: "Acer Laptop",
      author: "by Acer Company | 10 December 2020",
      price: 25000,
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQDXeW282eErNU24GqKbzLrBxgl9wEqaAVtRQGf1EAjUPxta4VfPxlN-0GP1zn8Jt3sTud0WKnETZI&usqp=CAc",
      amount: 1,
    },
    {
      id: 10,
      title: "Apple iPhone 14 Pro Max",
      author: "by Apple Company | 1 September 2021",
      price: 150000,
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQblixlfW79MzEIZsKttZLTLMAU_2pjzLjmjjMqrsp-v1xP37KvfdIklvpjOU-_JsPJB8l94bRtKA&usqp=CAc",
      amount: 1,
    },
    {
      id: 11,
      title: "Samsung Galaxy S22",
      author: "by Samsung Company | 14 December 2021",
      price: 67000,
      img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSeZd4ISa5PrWvYGb4WNM3wsE0_Nifh4Fb66AqTcHIplLwWWON9fVA5MnYTCIXWBLzCQ_TPpqg4muw&usqp=CAc",
      amount: 1,
    },
    {
      id: 12,
      title: "OnePlus Nord 2",
      author: "by OPPO Company| 1 January 2021",
      price: 29999,
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTinyG4M6UhEE7V8YfE7Y3EJFQbYqF2B2mn7_PKJZYp9IhYddkQooncT0XgHJWQE1Yngusdlq-ne8c&usqp=CAc",
      amount: 1,
    },
  ];
  
  export default list;